### ISSUE TITLE
Create models

### ISSUE THREAD

**Issue by bleakney** [rmwillow/theSocialScoop#4]
* User - (id, username, email, password)
* Review (within review, need static upvote--see Post.js in just-tech-news) - (id, content, user_id, date_watched, (include date_added in get reqs)
* Rating - (id, stars (x/5), show_id, user_id)
* Show - (id, title, genre, seasons, episodes)
* also index.js file

**Comment by meghankbock** [comment]
FYI - I've already created the review and vote model files
